import express, { Application } from "express";
import bodyParser from "body-parser";
import router from "../../routes/routes";
import swaggerUi from "swagger-ui-express";
const swaggerJsdoc = require("swagger-jsdoc");
import SwaggerDocument from "../../../swagger.json";
const app: Application = express();

const routesConfig = () => {
  app.use(function (req, res, next) {
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept");
    next();
  });

  app.use("/", router);

  const SwaggerOptions = {
    swaggerDefinition: {
      info: {
        title: "Test API",
        version: "1.0.0",
        description: "Test Express API with autogenerated swagger doc",
      },
    },
    // List of files to be processes. You can also set globs './routes/*.js'
    apis: ["../../routes/user/user.router.ts"],
  };

  const specs = swaggerJsdoc(SwaggerOptions);

  app.use("/swagger", swaggerUi.serve, swaggerUi.setup(SwaggerDocument));
};

const setMiddlewareConfig = () => {
  app.use(bodyParser.urlencoded({ extended: false }));
  app.use(bodyParser.json());
};

export const createServer = (port: string) => {
  setMiddlewareConfig();
  routesConfig();

  app.listen(port, () => {
    console.log("The server is running in " + port + " port");
  });
};
